name: AlpineJudge Tests

on: 
  push: 
      branches: [main]
      paths-ignore:
       - 'docs/**'
  pull_request:
      branches: [main]
      paths-ignore:
       - 'docs/**'

jobs:
  test: 
    runs-on: ubuntu-latest
            
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
        
      - name: Run Ajagent Tests
        working-directory: ajagent
        run: | 
          go vet -v ./...
          go test -race -v ./...
      
      - name: Run Shared module Tests
        working-directory: shared
        run: |
          go vet -v ./...
          go test -race -v ./...
        
      - name: Run Dispatcher Tests
        working-directory: dispatcher
        run: | 
          go vet -v ./...
          go test -race -v ./...

      - name: Run Runner Tests
        working-directory: runner
        run: | 
          sudo rm -rf /tmp/rabbitmq-testcontainers*
          sudo systemctl start containerd
          sudo ctr -n test-namespace images pull ghcr.io/smsadat1/alpinejudge/gcc:test
          sudo go vet -v ./...
          sudo go test -race -v ./...