name: AlpineJudge Tests

on: 
  push: 
      branches: [main]
      paths-ignore:
       - 'docs/**'
  pull_request:
      branches: [main]
      paths-ignore:
       - 'docs/**'

jobs:
  test: 
    runs-on: ubuntu-latest
            
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
        
      - name: Run Ajagent Integrity Tests
        working-directory: runner/ajagent/tests
        run: go test -v ./...
        
      - name: Run Unit Tests
        working-directory: tests/unit
        run: | 
          go mod tidy
          go test -v ./...

      - name: Run Integration Tests
        working-directory: tests/integration
        run: | 
          sudo systemctl start containerd
          sudo ctr -n test-namespace images pull ghcr.io/smsadat1/alpinejudge/gcc:test
          sudo go test -v -timeout 5m ./...

      - name: Run E2E Tests
        working-directory: tests/e2e
        run: | 
          chmod +x rune2e.sh
          sudo ./rune2e.sh